# Use the official Node.js version 20 image as the base image
FROM node:20

# Set the working directory inside the container to /app
# All following commands will run inside this directory
WORKDIR /app

# Copy package.json and package-lock.json files to the container
# This helps Docker cache dependencies if they don't change
COPY package*.json ./

# Install project dependencies inside the container
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Expose port 5000 so the container can communicate with the outside world
EXPOSE 5000

# Run the application using nodemon when the container starts
CMD ["npx", "nodemon", "src/server.js"]